"""add payment_method to transactions

Revision ID: 21f68ecb4ebd
Revises: 2857bc2e85d3
Create Date: 2026-07-27 15:22:17.977966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f68ecb4ebd'
down_revision: Union[str, Sequence[str], None] = '2857bc2e85d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
